package uno.anahata.asi.agi.tool;

import java.util.concurrent.Callable;

/**
 * The base class for all Java code generated by the AI model.
 * It extends {@link ToolContext} to provide access to the agi environment
 * and implements {@link Callable} for execution.
 * 
 * @author anahata
 */
public abstract class OnTheFlyAgiTool extends ToolContext implements Callable<Object>{
    
}
