/* Licensed under the Anahata Software License (ASL) v 108. See the LICENSE file for details. Força Barça! */
package uno.anahata.asi.agi.tool;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.function.Consumer;
import lombok.Getter;
import lombok.Setter;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.exception.ExceptionUtils;
import uno.anahata.asi.AbstractAsiContainer;
import uno.anahata.asi.agi.Agi;
import uno.anahata.asi.agi.message.AbstractModelMessage;
import uno.anahata.asi.internal.TikaUtils;
import uno.anahata.asi.agi.tool.spi.java.JavaMethodTool;
import uno.anahata.asi.agi.tool.spi.java.JavaMethodToolCall;
import uno.anahata.asi.agi.tool.spi.java.JavaMethodToolResponse;
import uno.anahata.asi.agi.tool.spi.java.JavaObjectToolkit;
import uno.anahata.asi.agi.resource.ResourceManager;

/**
 * The base class for Java code generated by the AI model or for toolkit
 * implementations. Extending this class provides convenient, thread-local
 * access to the current execution context, including logging, attachments, and
 * the parent agi session.
 *
 * @author anahata-gemini-pro-2.5
 */
@Slf4j
public class ToolContext {

    /**
     * The toolkit instance that owns this context.
     */
    @Getter
    @Setter
    protected JavaObjectToolkit toolkit;

    /**
     * Gets the current tool response from the thread-local context.
     *
     * @return The current response.
     * @throws IllegalStateException if called outside the scope of a tool
     * execution.
     */
    @Internal(value = "Gets the current tool response", requiresCapturedToolContext = true)
    public JavaMethodToolResponse getResponse() {
        JavaMethodToolResponse response = peekResponse();
        if (response == null) {
            throw new IllegalStateException("Cannot access ToolContext outside of a tool execution thread. Capture the context with getToolContext() into a final before entering a subthread.");
        }
        return response;
    }

    /**
     * Internal helper to retrieve the response if it exists, without throwing an 
     * exception. Supports both ThreadLocal and captured contexts.
     * 
     * @return The current response, or null.
     */
    protected JavaMethodToolResponse peekResponse() {
        return JavaMethodToolResponse.getCurrent();
    }

    /**
     * Checks if the current thread or this context instance is associated with 
     * an active tool execution.
     * 
     * @return true if a tool is executing.
     */
    @Internal(value = "Checks if executing within an active tool context", requiresCapturedToolContext = false)
    public boolean isToolExecution() {
        return peekResponse() != null;
    }

    /**
     * The id of model that is executing the tool.
     *
     * @return The id of model that is executing the tool.
     */
    @Internal(value = "The model ID of the executing model", requiresCapturedToolContext = true)
    public String getModelId() {
        return getModelMessage().getModelId();
        }
    
    /**
     * The id of model that is executing the tool.
     *
     * @return The id of model that is executing the tool.
     */
    @Internal(value = "The originating model message", requiresCapturedToolContext = true)
    public AbstractModelMessage getModelMessage() {
        return getResponse().getCall().getMessage();
    }

    /**
     * Returns a thread-safe snapshot of this context. If a tool response is
     * currently active on this thread, it returns a {@link CapturedToolContext}
     * that holds a fixed reference to that response, allowing it to be used in
     * subthreads, the EDT, or classloaders.
     *
     * @return A thread-safe ToolContext instance.
     */
    @Internal(value = "Returns a thread-safe snapshot of this context for propagation to subthreads", requiresCapturedToolContext = false)
    public ToolContext getToolContext() {
        JavaMethodToolResponse current = JavaMethodToolResponse.getCurrent();
        if (current != null) {
            return new CapturedToolContext(getToolkit(), current);
        }
        return this;
    }

    /**
     * Convenience method to get the current tool call that initiated this
     * execution.
     *
     * @return The current tool call.
     */
    @Internal(value = "The current tool call descriptor", requiresCapturedToolContext = true)
    public JavaMethodToolCall getCall() {
        return getResponse().getCall();
    }

    /**
     * Convenience method to get the metadata for the tool currently being
     * executed.
     *
     * @return The current tool metadata.
     */
    @Internal(value = "The current tool metadata", requiresCapturedToolContext = true)
    public JavaMethodTool getTool() {
        return getCall().getTool();
    }

    /**
     * Convenience method to get the application's global ToolManager.
     *
     * @return The ToolManager instance.
     */
    @Internal(value = "The application's global ToolManager instance", requiresCapturedToolContext = false)
    public ToolManager getToolManager() {
        if (toolkit != null) {
            return toolkit.getToolManager();
        }
        return getResponse().getAgi().getToolManager();
    }

    /**
     * Retrieves the singleton instance of a registered toolkit class.
     *
     * @param <T> The type of the toolkit.
     * @param toolkitClass The class of the toolkit to find.
     * @return The toolkit instance.
     * @throws IllegalArgumentException if the toolkit is not found.
     */
    @Internal(value = "Retrieves the singleton instance of a registered toolkit class", requiresCapturedToolContext = false)
    public <T> T getToolkit(Class<T> toolkitClass) {
        return getToolManager().getToolkitInstance(toolkitClass)
                .orElseThrow(() -> {
                    return new IllegalArgumentException("Toolkit not found: " + toolkitClass.getName());
                });
    }

    /**
     * Convenience method to get the parent agi container for the current
     * execution.
     *
     * @return The parent Agi instance.
     */
    @Internal(value = "The parent Agi session orchestrator", requiresCapturedToolContext = false)
    public Agi getAgi() {
        if (toolkit != null) {
            return toolkit.getToolManager().getAgi();
        }
        return getResponse().getAgi();
    }

    /**
     * Gets the current ASI container hosting this Agi container is running.
     *
     * @return The container-scoped attributes map.
     */
    @Internal(value = "The hosting ASI container", requiresCapturedToolContext = false)
    public AbstractAsiContainer getAsiContainer() {
        return getAgi().getConfig().getAsiContainer();
    }

    /**
     * Convenience method to get the application's ResourceManager.
     *
     * @return The ResourceManager instance.
     */
    @Internal(value = "The session ResourceManager instance", requiresCapturedToolContext = false)
    public ResourceManager getResourceManager() {
        return getAgi().getResourceManager();
    }

    /**
     * Convenience method to get the executor service for the current agi
     * session.
     *
     * @return The session-scoped ExecutorService.
     */
    @Internal(value = "The session-scoped ExecutorService", requiresCapturedToolContext = false)
    public ExecutorService getExecutorService() {
        return getAgi().getExecutor();
    }

    /**
     * Adds a standard log message to the current tool's response. If called
     * outside a tool execution thread, it logs to the SLF4J logger.
     *
     * @param message The log message to add.
     */
    @Internal(value = "Logs a standard message to the tool response logs", requiresCapturedToolContext = true)
    public void log(String message) {
        JavaMethodToolResponse response = peekResponse();
        if (response != null) {
            response.addLog(message);
        } else {
            log.warn("ToolContext log outside of tool execution context: [{}] {}", getClass().getSimpleName(), message);
        }
    }

    /**
     * Adds an error message to the current tool's response. If called outside a
     * tool execution thread, it logs to the SLF4J logger.
     *
     * @param message The error message to add.
     */
    @Internal(value = "Logs an error message to the tool response errors", requiresCapturedToolContext = true)
    public void error(String message) {
        JavaMethodToolResponse response = peekResponse();
        if (response != null) {
            response.addError(message);
        } else {
            log.error("ToolContext error outside of tool execution context: [{}] {}", getClass().getSimpleName(), message);
        }
    }
    
    /**
     * Adds an exceptions stack trace to the current tool's response. If called outside a
     * tool execution thread, it logs to the SLF4J logger.
     *
     * @param t The error message to add.
     */
    @Internal(value = "Logs an exception stack trace to the tool response errors", requiresCapturedToolContext = true)
    public void error(Throwable t) {
        JavaMethodToolResponse response = peekResponse();
        if (response != null) {
            response.addError(t);
        } else {
            log.error("ToolContext error outside of tool execution context on " + getClass().getSimpleName(), t);
        }
    }

    /**
     * Adds an error message and exception stack trace to the current tool's response.
     * If called outside a tool execution thread, it logs to the SLF4J logger.
     *
     * @param message The descriptive error message.
     * @param t The exception thrown.
     */
    @Internal(value = "Logs an error message and exception stack trace to the tool response errors", requiresCapturedToolContext = true)
    public void error(String message, Throwable t) {
        JavaMethodToolResponse response = peekResponse();
        if (response != null) {
            response.addError(message + ": " + ExceptionUtils.getStackTrace(t));
        } else {
            log.error("ToolContext error outside of tool execution context on " + getClass().getSimpleName() + ": " + message, t);
        }
    }

    /**
     * Attaches a binary blob to the current tool's response with source file path traceability.
     *
     * @param data The binary data to attach.
     * @param mimeType The MIME type of the data (e.g., 'image/png').
     * @param sourcePath The source file path on disk, or null.
     */
    @Internal(value = "Attaches binary data with source path to the tool response", requiresCapturedToolContext = true)
    public void addAttachment(byte[] data, String mimeType, Path sourcePath) {
        log("attaching " + data.length + "b mimeType=" + mimeType + " sourcePath=" + sourcePath);
        ToolResponseAttachment tra = getResponse().addAttachment(data, mimeType, sourcePath);
        log("attached " + tra);
    }

    /**
     * Attaches a binary blob to the current tool's response.
     *
     * @param data The binary data to attach.
     * @param mimeType The MIME type of the data (e.g., 'image/png').
     */
    @Internal(value = "Attaches binary data to the tool response", requiresCapturedToolContext = true)
    public void addAttachment(byte[] data, String mimeType) {
        getResponse().addAttachment(data, mimeType);
    }

    /**
     * Convenience method to attach a file to the current tool's response. The
     * MIME type is detected automatically using Tika.
     *
     * @param file The file to attach.
     * @throws IOException if the file cannot be read or the MIME type detection
     * fails.
     */
    @Internal(value = "Attaches a file to the tool response with auto-detected MIME type", requiresCapturedToolContext = true)
    public void addAttachment(File file) throws IOException {
        addAttachment(file.toPath());
    }

    /**
     * Convenience method to attach a file from a Path to the current tool's
     * response. The MIME type is detected automatically using Tika.
     *
     * @param path The path to the file to attach.
     * @throws IOException if the file cannot be read or the MIME type detection
     * fails.
     */
    @Internal(value = "Attaches a file from a Path to the tool response with auto-detected MIME type", requiresCapturedToolContext = true)
    public void addAttachment(Path path) throws IOException {
        byte[] data = Files.readAllBytes(path);
        String mimeType;
        try {
            mimeType = TikaUtils.detectMimeType(path.toFile());
        } catch (Exception e) {
            throw new IOException("Failed to detect MIME type for " + path, e);
        }
        addAttachment(data, mimeType, path);
    }
    
    /**
     * Gets a shared map for storing state across turns within the current agi
     * session.
     *
     * @return The turn-scoped attributes map.
     */
    @Internal(value = "Turn-scoped map for sharing state across tool calls within the same turn", requiresCapturedToolContext = true)
    public Map getTurnMap() {
        return getModelMessage().getTurnAttributes();
    }

    /**
     * Gets a shared map for storing state across turns within the current agi
     * session.
     *
     * @return The session-scoped attributes map.
     */
    @Internal(value = "Session-scoped persistent map across turns", requiresCapturedToolContext = false)
    public Map getSessionMap() {
        return getToolManager().getSessionAttributes();
    }

    /**
     * Gets a map for sharing objects across all sessions within the current ASI
     * container.
     *
     * @return The container-scoped attributes map.
     */
    @Internal(value = "Container-scoped map across sessions", requiresCapturedToolContext = false)
    public Map getAsiContainerMap() {
        return getAsiContainer().getContainerAttributes();
    }

    /**
     * Gets a static, application-scoped map for sharing objects across all
     * containers in the current JVM.
     *
     * @return The application-scoped attributes map.
     */
    @Internal(value = "JVM-wide static application map", requiresCapturedToolContext = false)
    public Map getApplicationMap() {
        return AbstractAsiContainer.applicationAttributes;
    }

    /**
     * Executes a task asynchronously in the session's executor service,
     * automatically propagating the current tool execution context to the
     * background thread.
     *
     * @param taskName A descriptive name for the task (used for thread naming).
     * @param task The task to execute.
     */
    @Internal(value = "Executes a task asynchronously with automatic context propagation", requiresCapturedToolContext = false)
    public void runAsync(String taskName, Runnable task) {
        final JavaMethodToolResponse response = getResponse();
        getExecutorService().submit(() -> {
            String oldName = Thread.currentThread().getName();
            Thread.currentThread().setName(oldName + " [" + taskName + "]");
            JavaMethodToolResponse.setCurrent(response);
            try {
                task.run();
            } catch (Throwable t) {
                log.error("Async tool task '{}' failed", taskName, t);
                try {
                    response.addError("Async task '" + taskName + "' failed: " + t.getMessage());
                } catch (Exception e) {
                    log.error("Failed to report async error to tool response", e);
                }
            } finally {
                JavaMethodToolResponse.setCurrent(null);
                Thread.currentThread().setName(oldName);
            }
        });
    }

    /**
     * Gets a thread-safe logging consumer that automatically propagates the
     * current tool execution context whenever a message is logged.
     *
     * @return A context-aware logging consumer.
     */
    @Internal(value = "Gets a context-aware thread-safe logging consumer", requiresCapturedToolContext = false)
    public Consumer<String> getThreadSafeLogger() {
        final JavaMethodToolResponse response = getResponse();
        return (msg) -> {
            JavaMethodToolResponse.setCurrent(response);
            try {
                log(msg);
            } finally {
                JavaMethodToolResponse.setCurrent(null);
            }
        };
    }

    /**
     * A thread-safe, immutable snapshot of a tool's execution context. Unlike
     * the standard ToolContext, which relies on a ThreadLocal to find the
     * active response, this implementation holds a fixed reference.
     */
    private static class CapturedToolContext extends ToolContext {

        private final JavaMethodToolResponse capturedResponse;

        private CapturedToolContext(JavaObjectToolkit toolkit, JavaMethodToolResponse response) {
            this.toolkit = toolkit;
            this.capturedResponse = response;
        }

        @Override
        public JavaMethodToolResponse getResponse() {
            // Bypass ThreadLocal! Use the captured reference directly.
            return capturedResponse;
        }

        @Override
        protected JavaMethodToolResponse peekResponse() {
            return capturedResponse;
        }

        @Override
        public ToolContext getToolContext() {
            return this; // Already captured
        }
    }

}
