/* Licensed under the Anahata Software License (ASL) v 108. See the LICENSE file for details. Força Barça! */
package uno.anahata.asi.agi.message;

import lombok.Getter;
import lombok.Setter;

/**
 * A specialized {@link TextPart} for content generated by an AI model.
 * <p>
 * Beyond standard text, this implementation is capable of encapsulating the 
 * model's internal 'Thinking Process'. It manages the visibility of these 
 * thoughts in the UI layer and maintains its own max-depth policy to 
 * optimize context window usage.
 * </p>
 *
 * @author anahata
 */
@Getter
@Setter
public class ModelTextPart extends TextPart implements ThoughtSignature {
    private byte[] thoughtSignature;
    private boolean thought;

    /**
     * Constructs a new ModelTextPart.
     *
     * @param message The model message this part belongs to. Must be a {@link AbstractModelMessage}.
     * @param text The text content.
     * @param thoughtSignature The signature of the thought process as a byte array.
     * @param thought Whether this part represents a thought process.
     */
    public ModelTextPart(AbstractModelMessage message, String text, byte[] thoughtSignature, boolean thought) {
        super(message, text);
        this.thoughtSignature = thoughtSignature;
        this.thought = thought;
        
        // Initialize expanded state for thoughts based on config. 
        if (thought) {
            setExpanded(getAgiConfig().isExpandThoughts());
        }
        
        // Leaf class publication
        message.addPart(this);
    }

    /** 
     * {@inheritDoc} 
     * <p>
     * Indicates whether this part contains internal model reasoning (thoughts) 
     * rather than direct conversational output.
     * </p>
     */
    @Override
    public boolean isThought() {
        return thought;
    }

    /**
     * {@inheritDoc}
     * Returns the default maximum depth for thoughts if this is a thought part,
     * otherwise falls back to the standard text part depth.
     */
    @Override
    protected int getDefaultMaxDepth() {
        if (isThought()) {
            return getAgiConfig().getDefaultThoughtPartMaxDepth();
        }
        return super.getDefaultMaxDepth();
    }
}
