/* Licensed under the Anahata Software License (ASL) v 108. See the LICENSE file for details. Força Barça! */
package uno.anahata.asi.agi.message.web;

import java.util.List;
import lombok.Getter;
import lombok.Setter;
import uno.anahata.asi.agi.message.AbstractModelMessage;
import uno.anahata.asi.agi.message.ModelTextPart;

/**
 * A specialized part representing a search query or search intent generated by the model.
 * <p>
 * This part captures the explicit "Web Search" action performed by the model 
 * on the server. While the results are typically aggregated in {@link GroundingMetadata}, 
 * this part maintains the chronological record of the search query within the conversation flow.
 * </p>
 * 
 * @author anahata
 */
@Getter
@Setter
public class WebSearchCallPart extends ModelTextPart {
    
    /**
     * The list of search queries generated by the model.
     */
    private List<String> queries;

    /**
     * Constructs a new ModelSearchCallPart.
     * 
     * @param message The model message that triggered the search.
     * @param displayText A human-readable summary of the search action.
     * @param queries The list of search queries executed.
     * @param thoughtSignature The signature of the thought process associated with this search, if any.
     */
    public WebSearchCallPart(AbstractModelMessage message, String displayText, List<String> queries, byte[] thoughtSignature) {
        super(message, displayText, thoughtSignature, false);
        this.queries = queries;
    }

    /**
     * {@inheritDoc}
     * <p>
     * Returns a formatted string indicating a hosted search call and its queries.
     * </p>
     */
    @Override
    public String asText() {
        return String.format("[Hosted Search Call] Queries: %s", queries);
    }

    /**
     * {@inheritDoc}
     * <p>
     * Returns the default maximum depth to keep a web search call part in context.
     * </p>
     */
    @Override
    protected int getDefaultMaxDepth() {
        return getAgiConfig().getDefaultWebSearchMaxDepth();
    }
}
